version: '3'
services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: admin
    restart: unless-stopped